# Generated by Django 5.2.2 on 2025-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
